"""auto

Revision ID: 53642a1a8a4c
Revises: 
Create Date: 2025-08-02 20:09:42.275225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.models.enums.user_role_enum import UserRoleEnum

# revision identifiers, used by Alembic.
revision: str = "53642a1a8a4c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


USER_ROLE_ENUM_NAME = "userroleenum"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=False),
        sa.Column("last_name", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("phone_number", sa.String(length=64), nullable=False),
        sa.Column("user_role", sa.Enum(*UserRoleEnum.values(), name=USER_ROLE_ENUM_NAME), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.execute(f"DROP TYPE {USER_ROLE_ENUM_NAME}")
    # ### end Alembic commands ###
